"""update models with live status and summary

Revision ID: cc57c112d45d
Revises: 5400732ce259
Create Date: 2026-08-18 21:23:21.242922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc57c112d45d'
down_revision: Union[str, Sequence[str], None] = '5400732ce259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('status', sa.String(), nullable=False))
    op.add_column('conversations', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('refund_approvals', sa.Column('category', sa.String(), nullable=True))
    op.add_column('refund_approvals', sa.Column('sentiment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund_approvals', 'sentiment')
    op.drop_column('refund_approvals', 'category')
    op.drop_column('conversations', 'updated_at')
    op.drop_column('conversations', 'summary')
    op.drop_column('conversations', 'status')
    # ### end Alembic commands ###
